//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinaryPractice
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medication
    {
        public int Id { get; set; }
        public string MedicationName { get; set; }
        public string MedicationNumber { get; set; }
        public string MedicationPrice { get; set; }
        public string MedicationQty { get; set; }
        public int VisitId { get; set; }
    
        public virtual Visit Visit { get; set; }
    }
}
